### ISSUE TITLE
Error running c2q_transfer_learning_ants_bees.ipynb w/ GPU

### ISSUE THREAD

**Issue by Jerry2001Qu** [XanaduAI/quantum-transfer-learning#4]
I'm trying to run the c2q_transfer_learning_ants_bees.ipynb notebook on a GPU. However, I keep encountering errors when running this line:

`model_hybrid = train_model(model_hybrid, criterion, optimizer_hybrid,exp_lr_scheduler, num_epochs=num_epochs)`

I've encountered the same error on my local machine, and Google Colab (both testing on a GPU). The code runs completely when run on a CPU.

Here's the traceback:
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-43-efc42279baeb> in <module>()
----> 1 model_hybrid = train_model(model_hybrid, criterion, optimizer_hybrid,exp_lr_scheduler, num_epochs=num_epochs)

2 frames
<ipython-input-42-9f2a4a230553> in train_model(model, criterion, optimizer, scheduler, num_epochs)
     38                         loss = criterion(outputs, labels)
     39                         if phase == 'train':
---> 40                             loss.backward()
     41                             optimizer.step()
     42 

/usr/local/lib/python3.6/dist-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
    183                 products. Defaults to ``False``.
    184         """
--> 185         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    186 
    187     def register_hook(self, hook):

/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
    125     Variable._execution_engine.run_backward(
    126         tensors, grad_tensors, retain_graph, create_graph,
--> 127         allow_unreachable=True)  # allow_unreachable flag
    128 
    129 

RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling 'cublasDgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)'
```

**Comment by co9olguy** [comment]
Thanks for reporting this @Jerry2001Qu!

Since PennyLane contains no explicit code for GPU execution (everything is delegated to the ML framework---PyTorch in this case), this is very likely a low-level issue with PyTorch. We can take a look to see if there's anything we can do, but I suspect we likely won't be able to offer much insight.

**Comment by Jerry2001Qu** [comment]
Hey, I was wondering if it's possible to find out what environment setup this code was originally written for? Ex: the version of Torch / PennyLane.

**Comment by Jerry2001Qu** [comment]
Ahh, I've gotten it working using package versions from when the original paper was released (December 2019).

torch==1.3.0
torchvision==0.4.2
Pillow==6.2.1
pennylane==0.7.0

**Comment by josh146** [comment]
Glad you got it sorted @Jerry2001Qu! If you wanted to make a PR to add the version requirements to the repo within a `requirements.txt` file, or even just to the readme, that would be greatly appreciated. Your detective skills going back in time to find the versions used would be very useful to others!

**Comment by Jerry2001Qu** [comment]
@josh146 The way you say that is too nice for me to ignore. I'll open a PR soon.
