### ISSUE TITLE
'tensorflow' has no attribute 'reset_default_graph'

### ISSUE THREAD

**Issue by mohitgour08** [XanaduAI/quantum-transfer-learning#9]
Hi, @andreamari 
I am trying to run q2c notebook but I am getting the below error in In[4]

[q2c_transfer_learning.ipynb](https://github.com/XanaduAI/quantum-transfer-learning/blob/cee63a927d812ce36d258317bab1459799ff66d9/q2c_transfer_learning.ipynb)

AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'
I am using versions:
tenserflow==2
torch==1.3.1
torchvision==0.4.2
Pillow==6.2.1
pennylane==0.7.0

can you help me resolving this error?
Thanks.

**Comment by andreamari** [comment]
I think the notebook was based on a previous version of TensorFlow below `2.0.0`.  See e.g. this link: 
https://stackoverflow.com/questions/62598537/module-tensorflow-has-no-atributte

I would suggest to follow the comments of the previous link or try to re-write the code in a way which is compatible with `tenserflow > 2`. Maybe it is just some minor syntax change in the usage of `tf.placeholder`, but at the moment I don't know.

**Comment by josh146** [comment]
Hi @mohitgour08, did Andrea's solution solve the issue you were having?

**Comment by mohitgour08** [comment]
@josh146  No, I tried using tf.compat.v1.placeholder and tf.compat.v1.reset_default_graph,  but then i am getting another error i.e tf.placeholder() is not compatible with eager execution.
if i disable eager execution it works but next for  In[7] it is asking to enable eager execution

**Comment by josh146** [comment]
@mohitgour08, from having a look at the example notebook, I believe it might be using the following versions of SF and TensorFlow:

- `strawberryfields==0.10`
- `tensorflow==1.3`

Could you try installing these versions in a local environment and see if the notebook runs?

**Comment by mohitgour08** [comment]
Thank You @josh146  I installed tensorflow==1.3 and strawberryfields==0.11.1 and it worked for me.
